extends:
  - google
  - plugin:react/recommended

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
    classes: true

parser: babel-eslint

plugins:
  - react

rules:
  max-len:
    - error
    -
      code: 120